version: "3"

services:
  mastodon:
    build:
      context: .
      args:
        - MASTODON_VERSION=v4.2.9
    env_file: .env.production
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
  caddy:
    image: caddy:2-alpine
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ./certs:/certs
  db:
    image: postgres:16-alpine
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=password
    healthcheck:
      test: ["CMD", "pg_isready"]
      interval: 2s
      timeout: 2s
      retries: 10
  redis:
    image: redis:7-alpine
