name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deply:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    env:
      REGISTRY: ghcr.io
      IMAGE_NAME: mkizka/mastodon-railway
      MASTODON_VERSION: v4.2.13
    steps:
      - uses: actions/checkout@v4
      - uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/setup-buildx-action@v3
      - uses: docker/metadata-action@v5
        id: meta
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=raw,value=${{ env.MASTODON_VERSION }}
            type=raw,value=latest
      - uses: docker/build-push-action@v6
        with:
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          build-args: MASTODON_VERSION=${{ env.MASTODON_VERSION }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
