name: Test

on:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: docker compose up -d
      - run: npx wait-on http://localhost:3000/health -t 30s
      - run: docker compose logs mastodon --tail=100
        if: failure()
