name: Test

on:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: docker compose up -d
      - run: npx wait-on https://mastodon.localhost/health -t 30s -v
      - run: npx wait-on https://mastodon.localhost -t 30s -v
      - run: docker compose logs mastodon --tail=100
        if: failure()
